/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ForyouRouteImport } from './routes/foryou'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistIdRouteImport } from './routes/playlist.$id'
import { Route as MixIdRouteImport } from './routes/mix.$id'
import { Route as ArtistIdRouteImport } from './routes/artist.$id'
import { Route as AlbumIdRouteImport } from './routes/album.$id'
import { Route as ApiStreamIdRouteImport } from './routes/api/stream.$id'
import { Route as ApiPublicStreamIdRouteImport } from './routes/api/public/stream.$id'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ForyouRoute = ForyouRouteImport.update({
  id: '/foryou',
  path: '/foryou',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistIdRoute = PlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MixIdRoute = MixIdRouteImport.update({
  id: '/mix/$id',
  path: '/mix/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistIdRoute = ArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIdRoute = AlbumIdRouteImport.update({
  id: '/album/$id',
  path: '/album/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamIdRoute = ApiStreamIdRouteImport.update({
  id: '/api/stream/$id',
  path: '/api/stream/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStreamIdRoute = ApiPublicStreamIdRouteImport.update({
  id: '/api/public/stream/$id',
  path: '/api/public/stream/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/foryou': typeof ForyouRoute
  '/library': typeof LibraryRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/stats': typeof StatsRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/mix/$id': typeof MixIdRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/api/stream/$id': typeof ApiStreamIdRoute
  '/api/public/stream/$id': typeof ApiPublicStreamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/foryou': typeof ForyouRoute
  '/library': typeof LibraryRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/stats': typeof StatsRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/mix/$id': typeof MixIdRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/api/stream/$id': typeof ApiStreamIdRoute
  '/api/public/stream/$id': typeof ApiPublicStreamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/downloads': typeof DownloadsRoute
  '/foryou': typeof ForyouRoute
  '/library': typeof LibraryRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/stats': typeof StatsRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/mix/$id': typeof MixIdRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/api/stream/$id': typeof ApiStreamIdRoute
  '/api/public/stream/$id': typeof ApiPublicStreamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/downloads'
    | '/foryou'
    | '/library'
    | '/player'
    | '/profile'
    | '/search'
    | '/stats'
    | '/album/$id'
    | '/artist/$id'
    | '/mix/$id'
    | '/playlist/$id'
    | '/api/stream/$id'
    | '/api/public/stream/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/downloads'
    | '/foryou'
    | '/library'
    | '/player'
    | '/profile'
    | '/search'
    | '/stats'
    | '/album/$id'
    | '/artist/$id'
    | '/mix/$id'
    | '/playlist/$id'
    | '/api/stream/$id'
    | '/api/public/stream/$id'
  id:
    | '__root__'
    | '/'
    | '/downloads'
    | '/foryou'
    | '/library'
    | '/player'
    | '/profile'
    | '/search'
    | '/stats'
    | '/album/$id'
    | '/artist/$id'
    | '/mix/$id'
    | '/playlist/$id'
    | '/api/stream/$id'
    | '/api/public/stream/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadsRoute: typeof DownloadsRoute
  ForyouRoute: typeof ForyouRoute
  LibraryRoute: typeof LibraryRoute
  PlayerRoute: typeof PlayerRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  StatsRoute: typeof StatsRoute
  AlbumIdRoute: typeof AlbumIdRoute
  ArtistIdRoute: typeof ArtistIdRoute
  MixIdRoute: typeof MixIdRoute
  PlaylistIdRoute: typeof PlaylistIdRoute
  ApiStreamIdRoute: typeof ApiStreamIdRoute
  ApiPublicStreamIdRoute: typeof ApiPublicStreamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foryou': {
      id: '/foryou'
      path: '/foryou'
      fullPath: '/foryou'
      preLoaderRoute: typeof ForyouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$id': {
      id: '/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof PlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mix/$id': {
      id: '/mix/$id'
      path: '/mix/$id'
      fullPath: '/mix/$id'
      preLoaderRoute: typeof MixIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$id': {
      id: '/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof ArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$id': {
      id: '/album/$id'
      path: '/album/$id'
      fullPath: '/album/$id'
      preLoaderRoute: typeof AlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/$id': {
      id: '/api/stream/$id'
      path: '/api/stream/$id'
      fullPath: '/api/stream/$id'
      preLoaderRoute: typeof ApiStreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream/$id': {
      id: '/api/public/stream/$id'
      path: '/api/public/stream/$id'
      fullPath: '/api/public/stream/$id'
      preLoaderRoute: typeof ApiPublicStreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadsRoute: DownloadsRoute,
  ForyouRoute: ForyouRoute,
  LibraryRoute: LibraryRoute,
  PlayerRoute: PlayerRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  StatsRoute: StatsRoute,
  AlbumIdRoute: AlbumIdRoute,
  ArtistIdRoute: ArtistIdRoute,
  MixIdRoute: MixIdRoute,
  PlaylistIdRoute: PlaylistIdRoute,
  ApiStreamIdRoute: ApiStreamIdRoute,
  ApiPublicStreamIdRoute: ApiPublicStreamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
